### ISSUE TITLE
Enum @@map support

### ISSUE THREAD

**Issue by Sebdevar** [olance/intellij-prisma#1]
Hi, I'm currently getting this weird error when mapping an enum to a DB type (which is supported based on the documentation):

PrismaTokenType.BRACE_R or PrismaTokenType.IDENTIFIER expected, got '@@map'

![Screenshot from 2020-11-13 16-01-45](https://user-images.githubusercontent.com/33068342/99120846-8ed65f00-25c9-11eb-99b4-599643c027a1.png)

**Comment by olance** [comment]
Hi @Sebdevar, thanks for the catch!

It seems my grammar is not expecting that kind of statement within the `enum` block.
Will fix ASAP! 🙂

**Comment by olance** [comment]
Fixed in master!
Plugin's new version is published and review by Jetbrains underway.

Sorry for the "ASAP" lasting 3 months 😑
