### ISSUE TITLE
Field name of 'type' causes problems

### ISSUE THREAD

**Issue by binary64** [olance/intellij-prisma#10]
```
model Blah {
  id         Int    @id @default(autoincrement())
  company_id Int
  name       String
  type       String

  @@map("blah")
}
```

shows like this: 
![image](https://user-images.githubusercontent.com/1680627/126683114-67370343-b14d-4fc9-8ac5-082df4ef5376.png)

**Comment by olance** [comment]
Thanks for the report @binary64, and sorry for the delay.

This error was due to my lexer definition, which was matching `type` as a block definition anywhere within the file.
I've just fixed this and will push a new version of the plugin ASAP!
