### ISSUE TITLE
Support Webstorm 2020.3

### ISSUE THREAD

**Issue by ammanvedi** [olance/intellij-prisma#2]
Need to. update to support latest version of webstorm

![Screenshot 2020-12-13 at 00 15 24](https://user-images.githubusercontent.com/1761300/101999793-7b0d3e00-3cd8-11eb-891a-dcb9eaf9ec1f.png)

If needed i am happy to help with this but i'd need a  indication of where to start

**Comment by olance** [comment]
Hey @ammanvedi thanks for the ping, I will be updating this ASAP!
Sorry for the wait :|

**Comment by ammanvedi** [comment]
> Hey @ammanvedi thanks for the ping, I will be updating this ASAP!
> Sorry for the wait :|

not a problem, thanks for the plugin!

**Comment by oliviermattei** [comment]
I'm expecting this update too ;) but I can't help XD

**Comment by olance** [comment]
Done!
Sorry for taking so long 😕 

Plugin's new version is awaiting Jetbrains' review

**Comment by ammanvedi** [comment]
Thank you much appreciated !!!
