### ISSUE TITLE
IDE validation issue with @@unique

### ISSUE THREAD

**Issue by rwitchell** [olance/intellij-prisma#4]
test with:
```prisma
model Foo {
  id        String @id
  firstName String?
  lastName  String?
  
  @@unique([firstName, lastName])
}
```

![image](https://user-images.githubusercontent.com/5378642/112802142-8b95c880-90bd-11eb-8281-9b476755ab21.png)

**Comment by olance** [comment]
Thanks for the report!

`@unique`/`@@unique` have been added "recently" (not so recent anymore...) – will update the plugin to take them into account!

**Comment by olance** [comment]
Update 1.0.3 of the plugin has been pushed to Jetbrains Plugins and is awaiting approval!
