### ISSUE TITLE
Support for intelliJ 2021 products

### ISSUE THREAD

**Issue by rwitchell** [olance/intellij-prisma#5]
Hello Olivier,

Hoping to see support for latest intelliJ versions?

**Comment by olance** [comment]
Hi @rwitchell!

Yes, finally getting some time off work and will be able to give some love to the plugin again :)

**Comment by rwitchell** [comment]
amazing - thanks for the reply and happy to bug test 🙂

**Comment by olance** [comment]
Update 1.0.3 of the plugin has been pushed to Jetbrains Plugins and is awaiting approval!
