### ISSUE TITLE
Support for Native types mapping

### ISSUE THREAD

**Issue by MarcioBarrientos** [olance/intellij-prisma#6]
Using:
Webstorm 2021.1
Prisma support 1.0.3.201
Prisma 2.21.2

Native types mapping like @db.Text doesn't work with this plugin.
description String? @db.Text
throws this message:

<model block statement>, PrismaTokenType.DOUBLE_COMMENT, PrismaTokenType.ENTITY_NAME, PrismaTokenType.EOL, PrismaTokenType.TRIPLE_COMMENT or PrismaTokenType.} expected, got 'description'

**Comment by olance** [comment]
Thanks for the report @MarcioBarrientos, I guess that's because the plugin's grammar is not accepting dots in model attribute names!
Will fix ASAP!

**Comment by akmoulai** [comment]
```
model X {
  range                Json                  @default("{}")
}
```
@olance I've also found that the above wasn't supported; I think this is a recent development, I couldn't find the docs for Json but for DateTime as an example -> https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#default-value-for-a-datetime

I've also found this which may be of interest: https://github.com/prisma/prisma/issues/2556

Excellent plugin btw, thanks for that 👍

**Comment by Deadly0** [comment]
Faced the same promlem with `@db.VarChar(100)`. It would be nice to fix this

**Comment by olance** [comment]
~~So @JarekToro things are actually more complicated than your fix, I was a bit too quick in merging it ^^~~

~~What you changed is the regex for fields _modifiers_, e.g. `@default` or `@id`.~~
~~But what needs to be updated is the rule for type names, which is parsed as a basic `ENTITY_NAME` for now, and that does not allow `@`, `.` or even parentheses.~~

~~Working on a fix right now :)~~

Can't even read a spec right 😑 
It's all good, adding proper tests and preparing release

**Comment by frankda** [comment]
Use database trigger solved this, copy everything needed in auth schema to my own user table
