### ISSUE TITLE
non-JS generators don't work

### ISSUE THREAD

**Issue by steebchen** [olance/intellij-prisma#7]
When using [Prisma's Go client](https://github.com/prisma/prisma-client-go), the provider value is set to:

```schema.prisma
generator client {
    provider         = "go run github.com/prisma/prisma-client-go"
}
```

which results in this parsing error:

![image](https://user-images.githubusercontent.com/5013932/116783629-ee61f180-aab9-11eb-8358-f0f1267c3037.png)

**Comment by olance** [comment]
@steebchen sorry about this and about the delay.

My lexer definition wasn't solid enough on string parsing, I've just fixed this and will release a new version by tomorrow!

**Comment by steebchen** [comment]
No worries, thanks for the fix :)
